version: "3.8"
services:

  # gateway:
  #   image: nginx:1.19.8-alpine
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - backend
  #   volumes:
  #     - ./Gateway/nginx.conf:/etc/nginx/nginx.conf
  #     - ./Gateway/api_gateway.conf:/etc/nginx/api_gateway.conf
      
  # consumer-service:
  #   image: consumer-service:compose_build
  #   build:
  #     context: ./consumer-service
  #     dockerfile: Dockerfile
  #   networks:
  #     - backend
  #   environment:
  #     PORT: ${CONSUMER_SERVICE_PORT}
      
  # order-service:
  #   image: order-service:compose_build
  #   build:
  #     context: ./order-service
  #     dockerfile: Dockerfile
  #   networks:
  #     - backend
  #   environment:
  #     CONSUMER_SERVICE_DOMAIN: ${CONSUMER_SERVICE_DOMAIN}
  #     CONSUMER_SERVICE_PORT: ${CONSUMER_SERVICE_PORT}
  #     KITCHEN_SERVICE_DOMAIN: ${KITCHEN_SERVICE_DOMAIN}
  #     KITCHEN_SERVICE_PORT: ${KITCHEN_SERVICE_PORT}
  #     PORT: ${ORDER_SERVICE_PORT}

  user-service:
    image: user-service:compose_build
    build:
      context: ./user-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment: 
      PORT: ${user}

networks:
  backend:
    name: restuarant
    driver: bridge
