version: "3.8"
services:

  # gateway:
  #   image: nginx:1.19.8-alpine
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - backend
  #   volumes:
  #     - ./Gateway/nginx.conf:/etc/nginx/nginx.conf
  #     - ./Gateway/api_gateway.conf:/etc/nginx/api_gateway.conf
      
  # consumer-service:
  #   image: consumer-service:compose_build
  #   build:
  #     context: ./consumer-service
  #     dockerfile: Dockerfile
  #   networks:
  #     - backend
  #   environment:
  #     PORT: ${CONSUMER_SERVICE_PORT}
      
  # order-service:
  #   image: order-service:compose_build
  #   build:
  #     context: ./order-service
  #     dockerfile: Dockerfile
  #   networks:
  #     - backend
  #   environment:
  #     CONSUMER_SERVICE_DOMAIN: ${CONSUMER_SERVICE_DOMAIN}
  #     CONSUMER_SERVICE_PORT: ${CONSUMER_SERVICE_PORT}
  #     KITCHEN_SERVICE_DOMAIN: ${KITCHEN_SERVICE_DOMAIN}
  #     KITCHEN_SERVICE_PORT: ${KITCHEN_SERVICE_PORT}
  #     PORT: ${ORDER_SERVICE_PORT}
  api-gateway:
    restart: always
    image: nginx:1.19.8-alpine
    ports:
      - 8080:8080
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./api-gateway/api_gateway.conf:/etc/nginx/api_gateway.conf
  userDb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_USER: ${USER}
      POSTGRES_DB: ${NAME}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
    - 7000:5432
  postDb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PASSWORDP}
      POSTGRES_USER: ${USERP}
      POSTGRES_DB: ${NAMEP}
      POSTGRES_HOST_AUTH_METHOD: "trust"

  user-service:
    restart: always
    image: user-service:compose_build
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      PORT: ${USER_SERVICE_PORT}
      DB_PORT: ${DATABASE_PORT}
      DB_HOST: ${HOST}
      DB_USER: ${USER}
      DB_PASSWORD: ${PASSWORD}
      DB_NAME: ${NAME}
    depends_on:
      - userDb


  post-service:
    restart: always
    image: post-service:compose_build
    build:
      context: ./post-service
      dockerfile: DockerfileP
    environment:
      PORT: ${POST_SERVICE_PORT}
      DB_PORT: ${DATABASE_PORTP}
      DB_HOST: ${HOSTP}
      DB_USER: ${USERP}
      DB_PASSWORD: ${PASSWORDP}
      DB_NAME: ${NAMEP}
    depends_on:
      - postDb


    # volumes:
    #     - user_Db:/var/lib/postgresql/data
#networks:
#  backend:
#    name: restuarant
#    driver: bridge
